server:
  port: 8092
  servlet:
    context-path: /productService/
    
spring:
  main:
    banner-mode: "off"
  profiles:
    active:  default # default : to run application.yml file    &&  prod : to run application-prod.yml file
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
#   type: org.apache.tomcat.jdbc.pool.DataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/inventory?allowLoadLocalInfile=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    tomcat:
      initial-size: 10
      max-wait: 300000
      max-active: 200
      max-idle: 30
      min-idle: 5
      timeBetweenEvictionRunsMillis: 120000
      minEvictableIdleTimeMillis: 600000
      removeAbandoned: true
      removeAbandonedTimeout: 60


